### ISSUE TITLE
Question, why deliver this as a script package?

### ISSUE THREAD

**Issue by pauldotknopf** [adamralph/simple-targets-csharp#126]
Isn't there support for loading referencing normal nuget packages in dotnet-script and scriptcs?

**Comment by adamralph** [comment]
@pauldotknopf it's a good question.

The package started off as a set of helper scripts for a build.csx file in another repo. I then extracted these into something reusable for other scripts and simple-targets-csx was born. The nice thing about it was that I could work on changes to simple-targets-csx inside other repos, in the packages folder, using real build scripts to drive and test the changes. I'd then copy those changes back into the main package and release a new version.

However, this comes with a trade off. When the project starts getting larger, with lots of csx files `#load`ing others, the gaps in the tooling start to become apparent. Writing and running tests is more difficult.

For these reasons, I'm now experimenting with using a traditional binary package instead, named [Bullseye](https://github.com/adamralph/bullseye). This can be used from script, or it can be used from a regular .NET project, avoiding scripting altogether. I'm currently [spiking the latter approach](https://github.com/adamralph/liteguard/pull/168) and the results are promising.

**Comment by pauldotknopf** [comment]
Bingo! I'll give Bullseye a go!

Side question, any plans on supporting async tasks?

**Comment by adamralph** [comment]
@pauldotknopf Bullseye already supports async tasks. See https://github.com/adamralph/liteguard/blob/spike-bullseye/targets/Program.cs for sample usage. Note that some delegates are explicitly marked `async`, containing `await`(s), and other simply call another async method (`RunAsync()`). There are also sync overloads if you need them.

Note that [`SimpleExec`](https://www.nuget.org/packages/SimpleExec/) is a good package to use in combination with Bullseye. It wraps command line invocation for you.

For a complete sample of how to use both packages, and how to avoid using any kind of script runner, see the [spike branch for converting LiteGuard to using Bullseye](https://github.com/adamralph/liteguard/tree/spike-bullseye). It has a [trivial `build.cmd`](https://github.com/adamralph/liteguard/blob/spike-bullseye/build.cmd) which simply uses `dotnet run` to invoke the [targets project](https://github.com/adamralph/liteguard/tree/spike-bullseye/targets). The beauty of that is that it is a regular .NET project (using .NET Core 2.0), so full tooling is available in all IDE's, and no need for special runners.

**Comment by pauldotknopf** [comment]
Awesome!

I have been using ```dotnet script``` for my build stuff, but your right, nothing wrong with traditional ```dotnet run```. You'd also get better debug support from any .NET IDE.

I got to go through your libraries. I'm loving your work! I love simplicity, something the .NET community lacks, something that your projects are screaming at me. Many .NET libraries are too clever, broadly focused, typed weirdly (BECAUSE FLUENT API IS COOL!). That was my main drive for creating [Statik](https://github.com/pauldotknopf/statik/).

Another nice approach I've been doing with my build scripts is making the invocation using ```PowerArgs``` or ```CommandLineUtils```.

* ```./build.sh --help``` to list available parameters to build (configuration/version/etc).
* ```./build.sh --config Debug```, etc.

Any ways, I've followed you on Twitter.

Thanks for everything!

**Comment by pauldotknopf** [comment]
I just seen your from Switzerland. I'm going to be in Zurich later this month. Any recommendations on things to do, places to see?

**Comment by adamralph** [comment]
@pauldotknopf thank you for the kind words. Simplicity is indeed what I strive for, and it's often the toughest thing to achieve. As [Mark Twain said](https://www.goodreads.com/quotes/21422-i-didn-t-have-time-to-write-a-short-letter-so):

> I didn't have time to write a short letter, so I wrote a long one instead.

Will you be in Zurich on 29th May? If so I can thoroughly recommend coming along to https://dotnetday.ch/ - it's a one day, two track, conference with at least one track in English at any given time, and I'll be giving the closing keynote. It would be good to meet you in person!

**Comment by pauldotknopf** [comment]
I am there during that! However, I'm in Zurich on business too and that specific day I will be in meetings.

:(

Now I'm depressed. Thanks a lot...  ;)
