### ISSUE TITLE
Validate all requested targets up front

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-targets-csharp#47]
Currently, each requested target is executed, and an exception is thrown only when the first unknown requested target is iterated through.

~Breaking, since this will prevent known requested targets from running before the unknown requested target is iterated through.~

**Comment by blairconrad** [comment]
May I have this?

**Comment by adamralph** [comment]
@blairconrad absolutely, thanks!

**Comment by blairconrad** [comment]
From https://github.com/adamralph/simple-targets-csx/pull/94#pullrequestreview-39332101:

> In the case where more than one target does not exist, it would be nicer to report all of them in the exception message to avoid cycles of run, error, fix, run, error, fix, ...

**Comment by adamralph** [comment]
Removing the breaking label, since this only breaks a sad path scenario.
