### ISSUE TITLE
Validate dependencies up front

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-targets-csharp#48]
Currently, each requested target and dependency is executed, and an exception is thrown only when the first unknown dependency is iterated through.

~Breaking, since this will prevent known requested targets and dependencies from running before the unknown requested dependency is iterated through.~

**Comment by blairconrad** [comment]
May I have this?

**Comment by adamralph** [comment]
@blairconrad absolutely, thanks!

**Comment by blairconrad** [comment]
From https://github.com/adamralph/simple-targets-csx/pull/94#pullrequestreview-39332101:

> the exception message "Target z does not exist" would be cryptic to the user, who requested target x, and may not know about target z. I think it's probably necessary to express the dependency chain in the exception message.

**Comment by blairconrad** [comment]
@adamralph, I'm not against expressing the dependency chain in the exception message, but it does introduce some additional questions:

1. should we then only report on unknown dependencies that are reached from executed targets?
1. if an unknown dependency can be reached from multiple executed targets, should we output the chain for each executed target?
1. likewise, if a dependency is referenced via multiple paths from a single target, should we output each path?

You'd expressed concerned about the edit/run cycle in my original fix, hoping to avoid it by providing as much information as possible (e.g. the complete list of unknown targets) to the user when there's an error. If we follow that spirit, I think the answer to questions 2 and 3 would have to be "yes". And the first one perhaps "no"? If we've detected that an unknown dependency exists, even before the referencing target is called, it might be helpful to alert the user as soon as possible, no?

I'm happy to implement whatever output you'd like, but I do wonder if it's not mollycoddling a little bit.
If we detect all unknown dependencies up front, whether exercised or not, then once that feature is in place, the error should only crop up right after a user had altered a dependency chain. It should be fresh in their mind. In that case, perhaps a simple message indicating that 'target "actualtarget" depends on unknown target "unknown', repeated for each unknown dependency might be sufficient?

**Comment by adamralph** [comment]
Removing the breaking label, since this only breaks a sad path scenario.
