### ISSUE TITLE
Return a result object instead of throwing exceptions for failed targets

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-targets-csharp#49]
The main advantage of this is to avoid an unhandled exception polluting the console output of csi.exe.

This means that failed targets will be treated as a possible outcome rather than an exception, which I think makes sense. I.e. a test fails. This isn't an exception in the context of target running, but a desired outcome when the test is badly written or the code is dysfunctional.

**Comment by adamralph** [comment]
Unsure about this...

**Comment by blairconrad** [comment]
@adamralph, I'm not sure why you're unsure about this, but how do you feel about it in the case of missing targets or dependencies? I think for either case, a result object makes more sense.
Alternatively, a custom exception could be thrown  and when caught, its message could be output without a stack trace.

**Comment by adamralph** [comment]
@blairconrad the problem is that the script must signal to the runner (e.g. csi.exe) that the process should exit with a code other than zero. The only sane way of doing that, AFAIK, is to throw an exception.

**Comment by blairconrad** [comment]
Ah, I see. An alternative would be to return an error code at the end of the script, but the docs all specify invoking the targets as

```c#
Run(Args, targets);
```

not 

```c#
return Run(Args, targets);
```

**Comment by adamralph** [comment]
Oooh, you're correct! IIRC scriptcs didn't propagate the return value of a script as the exit code, but it looks like csi.exe does! It also _insists_ on an integer value, whereas scriptcs let you return anything and swallowed it. This certainly changes things.

I like your suggestion of simply printing the exception message without the stack trace.

**Comment by adamralph** [comment]
I guess [this PR](https://github.com/dotnet/roslyn/pull/23018) would remove the need for this.

**Comment by blairconrad** [comment]
It would take care of the "clean up the output" portion. However, if instead of letting the exception fly we wanted to print a nicely-formatted (including colour) error message, we still might want to make _some_ change. But perhaps that's a different issue.

**Comment by adamralph** [comment]
We already do this:

![image](https://user-images.githubusercontent.com/677704/32434275-8afbe288-c2d5-11e7-9659-b5b3a6932128.png)

**Comment by blairconrad** [comment]
For certain classes of errors it seems so, but not all. Suppose we have a missing dependency. Then:

![image](https://user-images.githubusercontent.com/3275797/32439195-a3aec4fe-c2bb-11e7-8b54-d9e358063fb4.png)

'Failed to run "default"' is nice and highlighted, but the actual cause of the message is not.

**Comment by blairconrad** [comment]
Oh, and in the example you gave, not throwing the exception might give the opportunity to avoid repeating the cause of the failure, if desired.

**Comment by adamralph** [comment]
Ah, good point about the other exceptions. In fact, the more I think about it, the more it probably does 
make sense to return an error code. Writing a script is kind of like writing a `Program.Main()`. I.e. you should be able to either let exceptions propagate, or catch and return an error code. The only slightly weird thing is that normally you wouldn't expect a _library_ to do that on your behalf. I.e. you'd make that decision yourself in the `Program.Main()`. I worry slightly that it will be too easy to just call `Run()` without returning the value to the script runner, and that will result in build success where there should be build failure. This could cause havoc in CI environments.

**Comment by adamralph** [comment]
I guess another option is to have some kind of helper, e.g.

```C#
return GetExitCode(() => Run(Args, targets));
```

**Comment by adamralph** [comment]
Other ideas:

```C#
return GetExitCode(Args, targets); // called instead of Run()

return TryRun(Args, targets);

return RunWithExitCode(Args, targets);
```

**Comment by blairconrad** [comment]
The danger of forgetting to return the error code is a big one.
But I expect most people (who do not already have build scripts) will just copy the quickstart and it'll all work out.

On that, I'm probably just slow, but I'm not sure what would prevent the user from omitting the return in any of the cases you listed, so I'm not sure how changing from a straight `Run` invocation helps.

**Comment by adamralph** [comment]
The idea is to convey, through the name, that the method will never throw, but return an exit/error code.

**Comment by adamralph** [comment]
...and in turn, that will imply that if you call the method and ignore the return value, the build script will always succeed and never fail.

**Comment by blairconrad** [comment]
OH! Thanks. Sorry, I thought there was an implied control flow change, not just "nudging the humans".

**Comment by adamralph** [comment]
Withdrawing this. The stack trace is useful, since it points out in which line of your script the exception was thrown. csi.exe is going to be fixed to [restrict the stack trace to the script only](https://github.com/dotnet/roslyn/pull/23029).
