### ISSUE TITLE
Show failed targets in stdout summary

### ISSUE THREAD

**Issue by adamralph** [adamralph/simple-targets-csharp#57]

**Comment by blairconrad** [comment]
From https://github.com/adamralph/simple-targets-csx/pull/94#pullrequestreview-39332101: 

> In the case where more than one target does not exist, it would be nicer to report all of them in the exception message to avoid cycles of run, error, fix, run, error, fix, ...

**Comment by adamralph** [comment]
Not really sure what I meant by this. Withdrawing. If the idea comes back into my head, I'll re-raise with a proper description.
