### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by filipw** [adamralph/simple-targets-csharp#83]
At the moment the code has a rather weird structure, which only works due to the internal implementation detail of CSI.

`simple-targets.csx` defines a class and `#loads` a `runner.csx`, which in turn loads other files.
All these dependencies *use* that class defined inside `simple-targets.csx` - a file they actually *know nothing about*.

This is semantically incorrect, and if you run code analysis against the `simple-targets.csx` dependency tree, these things will be flagged as errors. 
It just happens to work at runtime due to how scripting works under the hood.

IMHO it would be better to treat the code structure like regular scripted code, where a common class is defined in a common CSX, which all the consumers can `#load`. If anything, it also helps grokking the code better.

**Comment by adamralph** [comment]
So I guess you're saying that `Target` and `TargetDictionary` should be defined at the lowest "level" and `#load`ed by everything else? I totally agree! Thanks for pointing it out.

I wish I had some tooling which told me this... I wonder how I can enforce it. Perhaps I can just hack in the "execution" of each individual script file into `build.cmd` to make sure it `#loads` everything it refers to.

**Comment by filipw** [comment]
great. actually if you use VS Code, it would tell you exactly that during authoring

**Comment by adamralph** [comment]
I do use VS Code, but none of this magic ever seems to work for me. Do I need anything other than https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp ?

**Comment by filipw** [comment]
at the moment you need an empty project.json next to the "root" csx for OmniSharp to light up

**Comment by adamralph** [comment]
OK, thanks. It kind of works, but it seems very flaky. I'll have a play around and see what I can come up with.

**Comment by filipw** [comment]
can you please document what is flaky? 

At the moment it has the following limitations:
 - #load / #r are not watched, meaning including them will require Omnisharp restart (cmt+alt+p)
 - single #load per file is supported
 - go to metadata is not supported (Roslyn bug)

The rest should be on par with regular C# experience. You should get full intellisense, member navigation, reference counts, code formatting etc

**Comment by adamralph** [comment]
I think it's these two that are biting me:

 - #load / #r are not watched, meaning including them will require Omnisharp restart (cmt+alt+p)
 - single #load per file is supported

The first I can obviously work around, but the second is somewhat of a showstopper for my use case.

**Comment by filipw** [comment]
> The first I can obviously work around, but the second is somewhat of a showstopper for my use case.

👍 

there is an issue tracking this for a while now - I have a fix locally ready, just need to clean it up a bit and will PR soon

**Comment by filipw** [comment]
here https://github.com/OmniSharp/omnisharp-roslyn/pull/760
