### ISSUE TITLE
dependencies may be run multiple times

### ISSUE THREAD

**Issue by blairconrad** [adamralph/simple-targets-csharp#88]
Consider:

```c#
#load "packages/simple-targets-csx.5.2.0/simple-targets.csx"

using static SimpleTargets;

var targets = new TargetDictionary();
targets.Add("default", DependsOn("pack"), ()=>{});
targets.Add("pack", DependsOn("build", "readVersion"), ()=>{});
targets.Add("build", DependsOn("readVersion"), ()=>{});
targets.Add("readVersion", ()=>{});

Run(Args, targets);
```

When run, I see

```
simple-targets: Running "default"...
simple-targets/readVersion: Starting...
simple-targets/readVersion: Succeeded.
simple-targets/build: Starting...
simple-targets/build: Succeeded.
simple-targets/readVersion: Starting...
simple-targets/readVersion: Succeeded.
simple-targets/pack: Starting...
simple-targets/pack: Succeeded.
simple-targets/default: Starting...
simple-targets/default: Succeeded.
simple-targets: "default" succeeded.
```

`readVersion` is executed twice.

**Comment by blairconrad** [comment]
I think this is a bug.
You may consider it to be breaking, if someone's come to rely on the behaviour.

I'd be happy to work on this.

**Comment by adamralph** [comment]
@blairconrad thanks for raising this. Yes, this does sound like a bug! The dependency resolution was specifically supposed to avoid running a target if it had already been run. I'll review your PR ASAP.

**Comment by blairconrad** [comment]
Thanks, @adamralph. No particular rush.
I saw the attempt to avoid this situation. I think the problem is that it was evaluating which dependencies should be run, and then while running them, some of _them_ would invoke other dependencies that were further down the list, if you know what I mean. There may be a more sophisticated solution but "decide at the last instant" was achievable. And easy to reason about.
