### ISSUE TITLE
Add option to skip dependencies

### ISSUE THREAD

**Issue by blairconrad** [adamralph/simple-targets-csharp#92]
Sometimes you just don't need to build or restore, or whatever…

An options (e.g. `-s`) could be supplied and then only listed targets (or the default target) would be executed, in the order specified (still no duplicates, though).

**Comment by adamralph** [comment]
@blairconrad thanks for raising this. This is a feature I consider periodically but always find a reason to dismiss. Can you explain your use case?

**Comment by blairconrad** [comment]
Sure. It's not going to be incredibly frequent (but then again, probably neither is the need for `--dry-run`), but in my case, I was refactoring some tests. I wanted to run the whole test suite, but had no need to rebuild the production code, and my `integ` target depended on `build`. I've had similar experiences in the past when iterating on `pack`aging the result of a build. In those situations, I've resorted to editing my `build.csx` to remove the time-consuming dependencies, iterating, and then restoring the file.

Thanks for considering the change.

**Comment by adamralph** [comment]
I sympathise with the use case, and indeed, I'd find this useful for the same reasons. However, I now remember why I'm reluctant to add this: ultimately, it's a workaround for a deficiency in the dependencies/targets.

In both the examples you mention, the script is performing redundant actions, i.e. performing an unnecessary re-build before running the tests or creating the NuGet package. I'm assuming that the targets you refer to are "typical" .NET targets which delegate to MSBuild. When I've come across this myself, I've managed to convince myself that either MSBuild is misbehaving, i.e. not respecting the state of the current binaries and whether they need to be rebuilt WRT to the source files (this tends to happen correctly in VS) or I am invoking MSBuild in the wrong way which results in this misbehaviour. I.e. I may be calling the wrong _MSBuild_ target or incorrect command line params. However, I've never overcome my laziness/trepidation and investigated that fully.

Incidentally, in my experience, `dotnet.exe` _does_ seem to respect the source and binary state by default, and does not perform a rebuild when it doesn't need to. (It also already know the relationship between things like test and build so less, if any, deps need to be declared in the csx.)  I'm not sure about "new" msbuild, which works with the VS2017 csproj format.

**Comment by blairconrad** [comment]
> I'm not sure about "new" msbuild, which works with the VS2017 csproj format.

Anecdotally, it seems to rebuild everything all the freaking time.
There's also a deficiency in `dotnet xunit`, where it rebuilds, but that's definitely its fault.

Oh, I've also done it when I want to run tests in a loop, like when I was examining the threadsafety of the Nancy tests or the FakeItEasy specs. But again, that's an uncommon case.

**Comment by blairconrad** [comment]
(But my experience with the old `dotnet` aligned with yours.)

**Comment by blairconrad** [comment]
I may have been unfair to new msbuild. The ilmerge of Castle.Core into FakeItEasy is a more likely culprit, forcing the rebuild of FakeItEasy.Tests and FakeItEasy.IntegrationTests.

I don't think this counts as a misuse of msbuild. A weird situation for sure, but one that I am not sure is better worked around than by sometimes just skipping the dependencies.

**Comment by adamralph** [comment]
Ah, so the ILMerge is running unnecessarily. Can it be reworked to only run when necessary?

It is indeed very tempting to build this feature in but each time I revisit it, it turns out that it's a workaround for a problem in the build targets themselves.

**Comment by blairconrad** [comment]
> Ah, so the ILMerge is running unnecessarily. Can it be reworked to only run when necessary?

Possibly. I gave it a little effort this morning, but the best course to me seemed to be to move the merge to a post-build step, which for some reason is not expanding the macros.
Ah well. FakeItEasy is using `dotnet xunit`'s option to not rebuild, so there's not that much profit in pursuing the ilmerge problem.

**Comment by blairconrad** [comment]
Thanks for entertaining this notion. Since it's not a fit for the project, I'll close the issue.

**Comment by thomaslevesque** [comment]
I still think such an option would be useful. The problem isn't MSBuild, it's the fact that if you have a `pack` target which depends on `build` which depends on `clean`, there's no way to run `pack` without re-running `build`, which in turn requires running `clean`, which causes `build` to rebuild everything.

The workaround (which I use frequently with Cake) is to design targets with no dependencies, e.g. replace this:
```csharp
targets.Add(
    "pack",
    DependsOn("build", "outputDirectory", "pdbgit"),
    () =>
    {
        var version = ReadCmdOutput(".", gitversion, "/showvariable NuGetVersionV2");
        Cmd("dotnet", $"pack {fakeItEasyProjectPath} --configuration Release --no-build --output {outputDirectory} /p:Version={version}");
        Cmd(nuget, $"pack {analyzerNuspecPath} -Version {version} -OutputDirectory {outputDirectory} -NoPackageAnalysis");
    });
```
with this:
```csharp
targets.Add(
    "packOnly",
    () =>
    {
        var version = ReadCmdOutput(".", gitversion, "/showvariable NuGetVersionV2");
        Cmd("dotnet", $"pack {fakeItEasyProjectPath} --configuration Release --no-build --output {outputDirectory} /p:Version={version}");
        Cmd(nuget, $"pack {analyzerNuspecPath} -Version {version} -OutputDirectory {outputDirectory} -NoPackageAnalysis");
    });

targets.Add("pack", DependsOn("build", "outputDirectory", "pdbgit", "packOnly"));
```

But it makes a mess of the otherwise clean targets...

**Comment by adamralph** [comment]
I think the problem in that example is a bad dependency on `clean` from `build`. I.e. there is no reason for `build` to depend on `clean`. I know this is something that has historically existed for a long time in our build scripts, but I do think it's a fundamental mistake (and IIRC, it was my mistake). E.g. in xbehave, I no longer take that dependency.

However, even so I think this shouldn't be required if you get your dependencies right, and the third party tools you are calling out to behave correctly, [this Twitter thread](https://twitter.com/adamralph/status/887769530663133184) has just convinced me that this is worth doing, as a practical workaround for problems which can't be immediately solved. I still think that using this option is an indicator of problems, and those problems should be solved, removing the need to use this option, but I can see the practical use of it until those problems can be solved.
